MERGE INTO ROL R USING(
    SELECT 
    '' AS NOMBRE_S,
    0 AS ID_ROL_S
    FROM DUAL
) S ON (R.ID_ROL = S.ID_ROL_S)
WHEN MATCHED THEN
UPDATE SET
    R.NOMBRE = S.NOMBRE_S
WHEN NOT MATCHED THEN
INSERT (
    R.NOMBRE
)
VALUES (
    S.NOMBRE_S
);
    

MERGE INTO ROLACCESO RA USING(
SELECT
0 AS ID_ROL_RAS,
1 AS GRANTED_RAS,
1 AS ID_ACCESO_RAS
FROM DUAL
) RAS ON (RA.ID_ROL = RAS.ID_ROL_RAS AND RA.ID_ACCESO = RAS.ID_ACCESO_RAS)
WHEN MATCHED THEN
UPDATE SET RA.GRANTED = RAS.GRANTED_RAS WHERE RA.ID_ACCESO = RAS.ID_ACCESO_RAS
WHEN NOT MATCHED THEN
INSERT (
RA.ID_ROL,
RA.ID_ACCESO,
RA.GRANTED
) VALUES (
RAS.ID_ROL_RAS,
RAS.ID_ACCESO_RAS,
RAS.GRANTED_RAS
)