MERGE INTO PROVEEDOR P USING(
    SELECT 
        id_proveedor AS id_proveedor_s,
        primer_nombre AS primer_nombre_s,
        segundo_nombre AS segundo_nombre_s,
        primer_apellido AS primer_apellido_s,
        segundo_apellido AS segundo_apellido_s,
        otros_apellidos AS otros_apellidos_s,
        calle AS calle_s,
        colonia AS colonia_s,
        zona AS zona_s,
        ciudad AS ciudad_s,
        municipio AS municipio_s,
        departamento AS departamento_s,
        codigo_postal AS codigo_postal_s,
        telefono AS telefono_s,
        nit AS nit_s,
        dpi AS dpi_s,
        email AS email_s,
        usuario_creacion AS usuario_creacion_s,
        usuario_mod AS usuario_mod_s,
--        fecha_creacion AS fecha_creacion_s,
        fecha_mod AS fecha_mod_s,
        estado AS estado_s
    FROM DUAL 
) S ON (P.id_proveedor = S.id_proveedor_s)
WHEN MATCHED THEN
UPDATE SET
    P.primer_nombre = S.primer_nombre_s,
    P.segundo_nombre = S.segundo_nombre_s,
    P.primer_apellido = S.primer_apellido_s,
    P.segundo_apellido = S.segundo_apellido_s,
    P.otros_apellidos = S.otros_apellidos_s,
    P.calle = S.calle_s,
    P.colonia = S.colonia_s,
    P.zona = S.zona_s,
    P.ciudad = S.ciudad_s,
    P.municipio = S.municipio_s,
    P.departamento = S.departamento_s,
    P.codigo_postal = S.codigo_postal_s,
    P.telefono = S.telefono_s,
    P.nit = S.nit_s,
    P.dpi = S.dpi_s,
    P.email = S.email_s,
    P.usuario_mod = S.usuario_mod_s,
    P.fecha_mod = S.fecha_mod_s,
    P.estado = S.estado_s
WHEN NOT MATCHED THEN
    INSERT (
        P.primer_nombre,
        P.segundo_nombre,
        P.primer_apellido,
        P.segundo_apellido,
        P.otros_apellidos,
        P.calle,
        P.colonia,
        P.zona,
        P.ciudad,
        P.municipio,
        P.departamento,
        P.codigo_postal,
        P.telefono,
        P.nit,
        P.dpi,
        P.email,
        P.usuario_creacion,
        P.usuario_mod,
--        P.fecha_creacion,
        P.fecha_mod,
        P.estado
    )
    VALUES (
        S.primer_nombre_s,
        S.segundo_nombre_s,
        S.primer_apellido_s,
        S.segundo_apellido_s,
        S.otros_apellidos_s,
        S.calle_s,
        S.colonia_s,
        S.zona_s,
        S.ciudad_s,
        S.municipio_s,
        S.departamento_s,
        S.codigo_postal_s,
        S.telefono_s,
        S.nit_s,
        S.dpi_s,
        S.email_s,
        S.usuario_creacion_s,
        S.usuario_mod_s,
--        S.fecha_creacion_s,
        S.fecha_mod_s,
        S.estado_s
    )
