-- ***************************************************** DICCIONARIOS *******************************************************
-- CREACION DE LA SECUENCIA FORMAS DE PAGO
CREATE SEQUENCE SEQ_FORMA_PAGO
  START WITH 1 -- Valor inicial
  INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
  NOCACHE -- No almacenar valores en caché
  NOCYCLE;

-- CREACION DE LA TABLA FORMAS DE PAGO
CREATE TABLE FORMA_PAGO (
    ID_FORMA_PAGO NUMBER DEFAULT SEQ_FORMA_PAGO.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(50)
);

-- CREACION DE LA SECUENCIA DEPARTAMENTOS
CREATE SEQUENCE SEQ_DEPARTAMENTO
  START WITH 1 -- Valor inicial
  INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
  NOCACHE -- No almacenar valores en caché
  NOCYCLE;

-- CREACION DE LA TABLA DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO NUMBER DEFAULT SEQ_DEPARTAMENTO.NEXTVAL PRIMARY KEY,
    CODIGO VARCHAR(2) NOT NULL,
    NOMBRE VARCHAR(40)
);

-- CREACION DE LA SECUENCIA MUNICIPIOS
CREATE SEQUENCE SEQ_MUNICIPIO
  START WITH 1 -- Valor inicial
  INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
  NOCACHE -- No almacenar valores en caché
  NOCYCLE;

-- CREACION DE LA TABLA MUNICIPIOS
CREATE TABLE MUNICIPIO (
    ID_MUNICIPIO NUMBER DEFAULT SEQ_MUNICIPIO.NEXTVAL PRIMARY KEY,
    DEPARTAMENTO NUMBER NOT NULL,
    CODIGO VARCHAR(2) NOT NULL,
    NOMBRE VARCHAR(40),
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

-- CREACION DE LA SECUENCIA ROLES
CREATE SEQUENCE SEQ_ROL
  START WITH 1 -- Valor inicial
  INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
  NOCACHE -- No almacenar valores en caché
  NOCYCLE;

-- Creaci�n de la tabla roles
CREATE TABLE ROL (
    ID_ROL NUMBER DEFAULT SEQ_ROL.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(50)
);

-- CREACION DE LA SECUENCIA ACCESOS
CREATE SEQUENCE SEQ_ACCESO
  START WITH 1 -- Valor inicial
  INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
  NOCACHE -- No almacenar valores en caché
  NOCYCLE;

-- Creaci�n de la tabla accesos con relaci�n a usuarios y roles
CREATE TABLE ACCESOS (
    ID_ACCESO NUMBER DEFAULT SEQ_ACCESO.NEXTVAL PRIMARY KEY,
    ACCESO VARCHAR2(250) NOT NULL
);

-- CREACION DE LA SECUENCIA ROLES Y ACCESOS
CREATE SEQUENCE SEQ_ROL_ACCESO
  START WITH 1 -- Valor inicial
  INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
  NOCACHE -- No almacenar valores en caché
  NOCYCLE;

CREATE TABLE ROLACCESO (
    ID NUMBER DEFAULT SEQ_ROL_ACCESO.NEXTVAL PRIMARY KEY,
    ID_ROL NUMBER,
    ID_ACCESO NUMBER,
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    FOREIGN KEY (ID_ACCESO) REFERENCES ACCESOS(ID_ACCESO)
);

-- ***************************************************** TABLAS *******************************************************

-- CREACION DE LA SECUENCIA USUARIOS
CREATE SEQUENCE SEQ_USUARIO
  START WITH 1 -- Valor inicial
  INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
  NOCACHE -- No almacenar valores en caché
  NOCYCLE;

-- Creaci�n de la tabla usuarios
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER DEFAULT SEQ_USUARIO.NEXTVAL PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR2(50),
    PRIMER_NOMBRE VARCHAR2(100) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(100) NOT NULL,
    OTROS_APELLIDOS VARCHAR2(100),
    PASSWORD VARCHAR2(50),
 --normalizacion de direccion
    CALLE VARCHAR2(100),
    COLONIA VARCHAR2(100),
    ZONA VARCHAR2(50),
    CIUDAD VARCHAR2(50),
    MUNICIPIO NUMBER,
    FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO),
    DEPARTAMENTO NUMBER,
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CODIGO_POSTAL VARCHAR2(10),
    TELEFONO VARCHAR2(20),
    NIT VARCHAR2(12),
    DPI VARCHAR2(20),
    ID_ROL NUMBER,
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);

-- CREACION DE LA SECUENCIA CLIENTES
CREATE SEQUENCE SEQ_CLIENTE
  START WITH 1 -- Valor inicial
  INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
  NOCACHE -- No almacenar valores en caché
  NOCYCLE;

-- Creaci�n de la tabla Clientes
CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER DEFAULT SEQ_CLIENTE.NEXTVAL PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR2(100) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(100) NOT NULL,
    OTROS_APELLIDOS VARCHAR2(100),
 --normalizacion de direccion
    CALLE VARCHAR2(100),
    COLONIA VARCHAR2(100),
    ZONA VARCHAR2(50),
    CIUDAD VARCHAR2(50),
    MUNICIPIO NUMBER,
    FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO),
    DEPARTAMENTO NUMBER,
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CODIGO_POSTAL VARCHAR2(10),
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR(250),
    NIT VARCHAR2(12) UNIQUE,
    DPI VARCHAR2(20) UNIQUE,
 --auditoria
    USUARIO_CREACION NUMBER,
    FOREIGN KEY (USUARIO_CREACION) REFERENCES USUARIO(ID_USUARIO),
    USUARIO_MOD NUMBER,
    FOREIGN KEY (USUARIO_MOD) REFERENCES USUARIO(ID_USUARIO),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MOD DATE,
    ESTADO NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1))
);

-- CREACION DE LA SECUENCIA PROVEEDORES
CREATE SEQUENCE SEQ_PROVEEDOR
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

-- Creaci�n de la tabla vendedores
CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR NUMBER DEFAULT SEQ_PROVEEDOR.NEXTVAL PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR2(100) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(100) NOT NULL,
    OTROS_APELLIDOS VARCHAR2(100),
 --normalizacion de direccion
    CALLE VARCHAR2(100),
    COLONIA VARCHAR2(100),
    ZONA VARCHAR2(50),
    CIUDAD VARCHAR2(50),
    MUNICIPIO NUMBER,
    FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO),
    DEPARTAMENTO NUMBER,
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CODIGO_POSTAL VARCHAR2(10),
    TELEFONO VARCHAR2(20),
    NIT VARCHAR2(12) UNIQUE,
    DPI VARCHAR2(20) UNIQUE,
    EMAIL VARCHAR(250),
 --auditoria
    USUARIO_CREACION NUMBER NOT NULL,
    FOREIGN KEY (USUARIO_CREACION) REFERENCES USUARIO(ID_USUARIO),
    USUARIO_MOD NUMBER NOT NULL,
    FOREIGN KEY (USUARIO_MOD) REFERENCES USUARIO(ID_USUARIO),
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FECHA_MOD DATE,
    ESTADO NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1))
);

--CREACION DE LA SECUENCIA PRODUCTOS
CREATE SEQUENCE SEQ_PRODUCTO
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

-- Creaci�n de la tabla Productos
CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER DEFAULT SEQ_PRODUCTO.NEXTVAL PRIMARY KEY,
    ID_PROVEEDOR NUMBER,
    CODIGO VARCHAR2(20) UNIQUE NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    PRECIO NUMBER NOT NULL,
    STOCK NUMBER NOT NULL,
 --auditoria
    USUARIO_CREACION NUMBER,
    FOREIGN KEY (USUARIO_CREACION) REFERENCES USUARIO(ID_USUARIO),
    USUARIO_MOD NUMBER,
    FOREIGN KEY (USUARIO_MOD) REFERENCES USUARIO(ID_USUARIO),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MOD DATE,
    ESTADO NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1)),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

-- CREACION DE LA SECUENCIA SUCURSAL
CREATE SEQUENCE SEQ_SUCURSAL
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

-- CREACION DE LA TABLA SUCURSAL
CREATE TABLE SUCURSAL (
    ID_SUCURSAL NUMBER DEFAULT SEQ_SUCURSAL.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(100),
 --normalizacion de direccion
    CALLE VARCHAR2(100),
    COLONIA VARCHAR2(100),
    ZONA VARCHAR2(50),
    CIUDAD VARCHAR2(50),
    MUNICIPIO NUMBER,
    FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO),
    DEPARTAMENTO NUMBER,
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CODIGO_POSTAL VARCHAR2(10),
    TELEFONO VARCHAR2(20),
 --auditoria
    USUARIO_CREACION NUMBER,
    FOREIGN KEY (USUARIO_CREACION) REFERENCES USUARIO(ID_USUARIO),
    USUARIO_MOD NUMBER,
    FOREIGN KEY (USUARIO_MOD) REFERENCES USUARIO(ID_USUARIO),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MOD DATE,
    ESTADO NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1))
);

-- CREACION DE LA SECUENCIA VENTAS
CREATE SEQUENCE SEQ_VENTA
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

-- CREACION DE LA TABLA VENTAS
CREATE TABLE VENTA (
    ID_VENTA NUMBER DEFAULT SEQ_VENTA.NEXTVAL PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ID_FORMA_PAGO NUMBER NOT NULL,
    ID_SUCURSAL NUMBER,
    GUID VARCHAR2(250) UNIQUE NOT NULL,
    FECHA_VENTA DATE NOT NULL,
    TOTAL NUMBER(10, 2),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_FORMA_PAGO) REFERENCES FORMA_PAGO(ID_FORMA_PAGO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

-- CREACION DE LA SECUENCIA DETALLE DE VENTA
CREATE SEQUENCE SEQ_DETALLE_VENTA
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

-- CREACION DE LA TABLA DETALLE DE VENTAS
CREATE TABLE DETALLE_VENTA (
    ID_DETALLE_VENTA NUMBER DEFAULT SEQ_DETALLE_VENTA.NEXTVAL PRIMARY KEY,
    ID_VENTA NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER(10, 2),
    DESCUENTO NUMBER,
    IMPUESTOS NUMBER,
    SUBTOTAL NUMBER,
    TOTAL NUMBER(10, 2),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID_VENTA)
);

-- CREACION DE LA SECUENCIA COMPRAS
CREATE SEQUENCE SEQ_COMPRA
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

-- CREACION DE LA TABLA COMPRAS
CREATE TABLE COMPRA (
    ID_COMPRA NUMBER DEFAULT SEQ_COMPRA.NEXTVAL PRIMARY KEY,
    ID_PROVEEDOR NUMBER NOT NULL,
    FECHA_COMPRA DATE NOT NULL,
    TOTAL NUMBER(10, 2),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
 --auditoria
    USUARIO_CREACION NUMBER,
    FOREIGN KEY (USUARIO_CREACION) REFERENCES USUARIO(ID_USUARIO),
    USUARIO_MOD NUMBER,
    FOREIGN KEY (USUARIO_MOD) REFERENCES USUARIO(ID_USUARIO),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MOD DATE,
    ESTADO NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1))
);

-- CREACION DE LA SECUENCIA DETALLE DE COMPRA
CREATE SEQUENCE SEQ_DETALLE_COMPRA
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

-- CREACION DE LA TABLA DETALLE DE COMPRAS
CREATE TABLE DETALLE_COMPRA (
    ID_DETALLE_COMPRA NUMBER DEFAULT SEQ_DETALLE_COMPRA.NEXTVAL PRIMARY KEY,
    ID_COMPRA NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER(10, 2),
    DESCUENTO NUMBER,
    IMPUESTOS NUMBER,
    SUBTOTAL NUMBER,
    TOTAL NUMBER(10, 2),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA)
);

--CREACION DE LA SECUENCIA ORDEN DE COMPRA
CREATE SEQUENCE SEQ_ORDEN_COMPRA
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

--CREACION DE LA TABLA ORDENES DE COMPRA
CREATE TABLE ORDEN_COMPRA (
    ID_ORDEN_COMPRA NUMBER DEFAULT SEQ_ORDEN_COMPRA.NEXTVAL PRIMARY KEY,
    ID_PROVEEDOR NUMBER,
    FECHA_ORDEN DATE,
    TOTAL NUMBER,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

-- CREACION DE LA SECUENCIA COLABORADORES
CREATE SEQUENCE SEQ_COLABORADOR
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

CREATE TABLE COLABORADOR (
    ID_COLABORADOR NUMBER DEFAULT SEQ_COLABORADOR.NEXTVAL PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR2(100) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(100) NOT NULL,
    OTROS_APELLIDOS VARCHAR2(100),
 --normalizacion de direccion
    CALLE VARCHAR2(100),
    COLONIA VARCHAR2(100),
    ZONA VARCHAR2(50),
    CIUDAD VARCHAR2(50),
    MUNICIPIO NUMBER,
    FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO),
    DEPARTAMENTO NUMBER,
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CODIGO_POSTAL VARCHAR2(10),
    TELEFONO VARCHAR2(20),
    NIT VARCHAR2(12) UNIQUE,
    DPI VARCHAR2(20) UNIQUE,
    EMAIL VARCHAR(250),
 --auditoria
    USUARIO_CREACION NUMBER,
    FOREIGN KEY (USUARIO_CREACION) REFERENCES USUARIO(ID_USUARIO),
    USUARIO_MOD NUMBER,
    FOREIGN KEY (USUARIO_MOD) REFERENCES USUARIO(ID_USUARIO),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MOD DATE,
    ESTADO NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1))
);

-- CREACION DE LA SECUENCIA BODEGAS
CREATE SEQUENCE SEQ_BODEGA
    START WITH 1 -- Valor inicial
    INCREMENT BY 1 -- Incremento en cada siguiente valor
MINVALUE 1 -- Valor mínimo permitido
MAXVALUE 999999999 -- Valor máximo
    NOCACHE -- No almacenar valores en caché
    NOCYCLE;

-- CREACION DE LA TABLA BODEGAS
CREATE TABLE BODEGA(
    ID_BODEGA NUMBER DEFAULT SEQ_BODEGA.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(100),
 --normalizacion de direccion
    CALLE VARCHAR2(100),
    COLONIA VARCHAR2(100),
    ZONA VARCHAR2(50),
    CIUDAD VARCHAR2(50),
    MUNICIPIO NUMBER,
    FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO),
    DEPARTAMENTO NUMBER,
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CODIGO_POSTAL VARCHAR2(10),
    TELEFONO VARCHAR2(20),
 --auditoria
    USUARIO_CREACION NUMBER,
    FOREIGN KEY (USUARIO_CREACION) REFERENCES USUARIO(ID_USUARIO),
    USUARIO_MOD NUMBER,
    FOREIGN KEY (USUARIO_MOD) REFERENCES USUARIO(ID_USUARIO),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MOD DATE,
    ESTADO NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1))
);