--SELECT 'DROP TABLE ' || table_name || ' CASCADE CONSTRAINTS;' 
--FROM user_tables;

DROP TABLE FORMA_PAGO CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE MUNICIPIO CASCADE CONSTRAINTS;
DROP TABLE ACCESOS CASCADE CONSTRAINTS;
DROP TABLE ROL CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE EMPRESA CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE PUNTO_VENTA CASCADE CONSTRAINTS;
DROP TABLE VENTA CASCADE CONSTRAINTS;
DROP TABLE DETALLE_VENTA CASCADE CONSTRAINTS;
DROP TABLE COMPRA CASCADE CONSTRAINTS;
DROP TABLE DETALLE_COMPRA CASCADE CONSTRAINTS;
DROP TABLE ORDEN_COMPRA CASCADE CONSTRAINTS;
DROP TABLE COTIZACION CASCADE CONSTRAINTS;
DROP TABLE COLABORADOR CASCADE CONSTRAINTS;
DROP TABLE CUADRE CASCADE CONSTRAINTS;
DROP TABLE BITACORA CASCADE CONSTRAINTS;
DROP TABLE BODEGA CASCADE CONSTRAINTS;
DROP TABLE TRASLADO CASCADE CONSTRAINTS;
DROP TABLE ENVIO CASCADE CONSTRAINTS;
