--SELECT 'DROP SEQUENCE ' || sequence_name || ';' 
--FROM user_sequences;

DROP SEQUENCE SEQ_ACCESO;
DROP SEQUENCE SEQ_BITACORA;
DROP SEQUENCE SEQ_BODEGA;
DROP SEQUENCE SEQ_CLIENTE;
DROP SEQUENCE SEQ_COLABORADOR;
DROP SEQUENCE SEQ_COMPRA;
DROP SEQUENCE SEQ_COTIZACION;
DROP SEQUENCE SEQ_CUADRE;
DROP SEQUENCE SEQ_DEPARTAMENTO;
DROP SEQUENCE SEQ_DETALLE_COMPRA;
DROP SEQUENCE SEQ_DETALLE_VENTA;
DROP SEQUENCE SEQ_EMPRESA;
DROP SEQUENCE SEQ_ENVIO;
DROP SEQUENCE SEQ_FORMA_PAGO;
DROP SEQUENCE SEQ_MUNICIPIO;
DROP SEQUENCE SEQ_ORDEN_COMPRA;
DROP SEQUENCE SEQ_PRODUCTO;
DROP SEQUENCE SEQ_PROVEEDOR;
DROP SEQUENCE SEQ_PUNTO_VENTA;
DROP SEQUENCE SEQ_ROL;
DROP SEQUENCE SEQ_SUCURSAL;
DROP SEQUENCE SEQ_TRASLADO;
DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_VENDEDOR;
DROP SEQUENCE SEQ_VENTA;