INSERT INTO ROL(NOMBRE) VALUES ('ADMINISTRADOR');

INSERT INTO ACCESOS(acceso) VALUES ('COLABORADORES');
INSERT INTO ACCESOS(acceso) VALUES ('USUARIOS');
INSERT INTO ACCESOS(acceso) VALUES ('ROLES');
INSERT INTO ACCESOS(acceso) VALUES ('CLIENTES');
INSERT INTO ACCESOS(acceso) VALUES ('PROVEEDORES');
INSERT INTO ACCESOS(acceso) VALUES ('COMPRAS');
INSERT INTO ACCESOS(acceso) VALUES ('VENTAS');
INSERT INTO ACCESOS(acceso) VALUES ('INVENTARIO');
INSERT INTO ACCESOS(acceso) VALUES ('ORDENES_COMPRA');


SELECT * FROM ROL;

SELECT * FROM ACCESOS;