-- Usuario 1
INSERT INTO USUARIO (
    NOMBRE_USUARIO,
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    PASSWORD,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    NIT,
    DPI,
    ID_ROL
) VALUES (
    'usuario1',
    'Juan',
    'Carlos',
    'Perez',
    'Gonzalez',
    NULL,
    'clave123',
    '6ta Avenida',
    'San Cristobal',
    'Zona 8',
    'Ciudad de Guatemala',
    '01',
    1,
    '01010',
    '5555-5555',
    '89097891282',
    '1234567890123',
    1
);

-- Usuario 2
INSERT INTO USUARIO (
    NOMBRE_USUARIO,
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    PASSWORD,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    NIT,
    DPI,
    ID_ROL
) VALUES (
    'usuario2',
    'Maria',
    'Isabel',
    'Lopez',
    'Garcia',
    NULL,
    'clave456',
    '10ma Calle',
    'La Reforma',
    'Zona 10',
    'Ciudad de Guatemala',
    '02',
    2,
    '01020',
    '5555-5555',
    '891301202101',
    '9876543210123',
    2
);