-- GUATEMALA
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '01', 'GUATEMALA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '02', 'SANTA CATARINA PINULA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '03', 'SAN JOSE PINULA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '04', 'SAN JOSE DEL GOLFO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '05', 'PALENCIA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '06', 'CHINAUTLA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '07', 'SAN PEDRO AYAMPUC');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '08', 'MIXCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '09', 'SAN PEDRO SACATEPEQUEZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '10', 'SAN JUAN SACATEPEQUEZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '11', 'SAN RAYMUNDO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '12', 'CHUARRANCHO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '13', 'FRAIJANES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '14', 'AMATITLAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '15', 'VILLA NUEVA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '16', 'VILLA CANALES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (1, '17', 'SAN MIGUEL PETAPA');

-- EL PROGRESO
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (2, '01', 'GUASTATOYA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (2, '02', 'MORAZAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (2, '03', 'SAN AGUSTIN ACASAGUASTLAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (2, '04', 'SAN CRISTOBAL ACASAGUASTLAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (2, '05', 'EL JICARO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (2, '06', 'SANSARE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (2, '07', 'SANARATE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (2, '08', 'SAN ANTONIO LA PAZ');

--SACATEPEQUEZ
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '01', 'ANTIGUA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '02', 'JOCOTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '03', 'PASTORES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '04', 'SUMPANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '05', 'SANTO DOMINGO XENACOJ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '06', 'SANTIAGO SACATEPEQUEZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '07', 'SAN BARTOLOME MILPAS ALTAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '08', 'SAN LUCAS SACATEPEQUEZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '09', 'SANTA LUCIA MILPAS ALTAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '10', 'MAGDALENA MILPAS ALTAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '11', 'SANTA MARIA DE JESUS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '12', 'CIUDAD VIEJA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '13', 'SAN MIGUEL DUENAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '14', 'ALOTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '15', 'SAN ANTONIO AGUAS CALIENTES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (3, '16', 'SANTA CATARINA BARAHONA');


--CHIMALTENANGO
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '01', 'CHIMALTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '02', 'SAN JOSE POAQUIL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '03', 'SAN MARTIN JILOTEPEQUE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '04', 'SAN JUAN COMALAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '05', 'SANTA APOLONIA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '06', 'TECPAN GUATEMALA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '07', 'PATZUN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '08', 'AN MIGUEL POCHUTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '09', 'PATZICIA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '10', 'SANTA CRUZ BALANYA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '11', 'ACATENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '12', 'SAN PEDRO YEPOCAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '13', 'SAN ANDRES ITZAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '14', 'PARRAMOS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '15', 'ZARAGOZA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (4, '16', 'EL TEJAR');

--ESCUINTLA
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '01', 'ESCUINTLA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '02', 'SANTA LUCIA COTZUMALGUAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '03', 'LA DEMOCRACIA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '04', 'SIQUINALA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '05', 'MASAGUA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '06', 'TIQUISATE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '07', 'LA GOMERA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '08', 'GUANAGAZAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '09', 'SAN JOSE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '10', 'IZTAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '11', 'PALIN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '12', 'SAN VICENTE PACAYA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (5, '13', 'NUEVA CONCEPCION ');

 --SANTA ROSA
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '01', 'CUILAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '02', 'BARBERENA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '03', 'SANTA ROSA DE LIMA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '04', 'CASILLAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '05', 'SAN RAFAEL LAS FLORES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '06', 'ORATORIO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '07', 'SAN JUAN TECUACO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '08', 'CHIQUIMULILLA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '09', 'TAXISCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '10', 'SANTA MARIA IXHUATAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '11', 'GUAZACAPAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '12', 'SANTA CRUZ NARANJO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '13', 'PUEBLO NUEVO VIÑAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (6, '14', 'NUEVA SANTA ROSA');

--SOLOLA
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '01', 'SOLOLA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '02', 'SAN JOSE CHACAYA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '03', 'SANTA MARIA VISITACION');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '04', 'SANTA LUCIA UTATLAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '05', 'NAHUALA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '06', 'SANTA CATARINA IXTAHUACAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '07', 'SANTA CLARA LA LAGUNA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '08', 'CONCEPCION');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '09', 'SAN ANDRES SEMETABAJ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '10', 'PANAJACHEL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '11', 'SANTA CATARINA PALOPO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '12', 'SAN ANTONIO PALOPO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '13', 'SAN LUCAS TOLIMAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '14', 'SANTA CRUZ LA LAGUNA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '15', 'SAN PABLO LA LAGUNA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '16', 'SAN MARCOS LA LAGUNA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '17', 'SAN JUAN LA LAGUNA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '18', 'SAN PEDRO LA LAGUNA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (7, '19', 'SANTIAGO ATITLAN');


--TOTONICAPAN
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (8, '01', 'TOTONICAPAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (8, '02', 'SAN CRISTOBAL TOTONICAPAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (8, '03', 'SAN FRANCISCO EL ALTO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (8, '04', 'SAN ANDRES XECUL ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (8, '05', 'MOMOSTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (8, '06', 'SANTA MARIA CHIQUIMULA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (8, '07', 'SANTA LUCIA LA REFORMA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (8, '08', 'SAN BARTOLO AGUAS CALIENTES');



--QUETZALTENANGO
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '01', 'QUETZALTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '02', 'SALCAJA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '03', 'OLINTEPEQUE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '04', 'SAN CARLOS SIJA ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '05', 'SIBILIA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '06', 'CABRICAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '07', 'CAJOLA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '08', 'SAN MIGUEL SIGUILA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '09', 'SAN JUAN OSTUNCALCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '10', 'SAN MATEO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '11', 'CONCEPCION CHIQUIRICHAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '12', 'SAN MARTIN SACATEPEQUEZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '13', 'ALMOLONGA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '14', 'CANTEL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '15', 'HUITAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '16', 'ZUNIL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '17', 'COLOMBA COSTA CUCA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '18', 'SAN FRANCISCO LA UNION');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '19', 'EL PALMAR');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '20', 'COATEPEQUE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '21', 'GENOVA COSTA CUCA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '22', 'FLORES COSTA CUCA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '23', 'LA ESPERANZA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (9, '24', 'PALESTINA DE LOS ALTOS');


--SUCHITEPEQUEZ
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '01', 'MAZATENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '02', 'CUYOTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '03', 'SAN FRANCISCO ZAPOTITLAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '04', 'SAN BERNARDINO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '05', 'SAN JOSE EL IDOLO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '06', 'SANTO DOMINGO SUCHITEPEQUEZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '07', 'SAN LORENZO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '08', 'SAMAYAC');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '09', 'SAN PABLO JOCOPILAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '10', 'SAN ANTONIO SUCHITEPEQUEZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '11', 'SAN MIGUEL PANAM');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '12', 'SAN GABRIEL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '13', 'CHICACAO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '14', 'PATULUL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '15', 'SANTA BARBARA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '16', 'SAN JUAN BAUTISTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '17', 'SANTO TOMAS LA UNION');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '18', 'ZUNILITO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '19', 'PUEBLO NUEVO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (10, '20', 'RIO BRAVO');


--RETALHULEU
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '01', 'RETALHULEU');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '02', 'SAN SEBASTIAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '03', 'SANTA CRUZ MULUA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '04', 'SAN MARTIN ZAPOTITLAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '05', 'SAN FELIPE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '06', 'SAN ANDRES VILLA SECA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '07', 'CHAMPERICO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '08', 'NUEVO SAN CARLOS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (11, '09', 'EL ASINTAL');


--SAN MARCOS
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '01', 'SAN MARCOS ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '02', 'SAN PEDRO SACATEPEQUEZ ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '03', 'SAN ANTONIO SACATEPEQUEZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '04', 'COMITANCILLO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '05', 'SAN MIGUEL IXTAHUACAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '06', 'CONCEPCION TUTUAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '07', 'TACANA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '08', 'SIBINAL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '09', 'TAJUMULCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '10', 'TEJUTLA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '11', 'SAN RAFAEL PIE DE LA CUESTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '12', 'NUEVO PROGRESO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '13', 'EL TUMBADOR');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '14', 'SAN JOSE EL RODEO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '15', 'MALACATAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '16', 'CATARINA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '17', 'AYUTLA (TECUN UMAN)');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '18', 'OCOS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '19', 'SAN PABLO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '20', 'EL QUETZAL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '21', 'LA REFORMA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '22', 'PAJAPITA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '23', 'IXCHIGUAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '24', 'SAN JOSE OJETENAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '25', 'SAN CRISTOBAL CUCHO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '26', 'SIPACAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '27', 'ESQUIPULAS PALO GORDO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '28', 'RIO BLANCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (12, '29', 'SAN LORENZO');


--HUEHUETENANGO
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '01', 'HUEHUETENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '02', 'CHIANTLA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '03', 'MALACATANCITO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '04', 'CUILCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '05', 'NENTON');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '06', 'SAN PEDRO NECTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '07', 'JACALTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '08', 'SAN PEDRO SOLOMA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '09', 'SAN ILDEFONSO IXTAHUACAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '10', 'SANTA BARBARA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '11', 'LA LIBERTAD');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '12', 'LA DEMOCRACIA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '13', 'SAN MIGUEL ACATAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '14', 'SAN RAFAEL LA INDEPENDENCIA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '15', 'TODOS SANTOS CUCHUMATAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '16', 'SAN JUAN ATITAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '17', 'SANTA EULALIA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '18', 'SAN MATEO IXTATAN ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '19', 'COLOTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '20', 'SAN SEBASTIAN HUEHUETENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '21', 'TECTITAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '22', 'CONCEPCION HUISTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '23', 'SAN JUAN IXCOY');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '24', 'SAN ANTONIO HUISTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '25', 'SAN SEBASTIAN COATAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '26', 'SANTA CRUZ BARILLAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '27', 'AGUACATAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '28', 'SAN RAFAEL PETZAL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '29', 'SAN GASPAR IXCHIL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '30', 'SANTIAGO CHIMALTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '31', 'SANTA ANA HUISTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (13, '32', 'UNIÓN CANTINIL');


--QUICHE
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '01', 'SANTA CRUZ DEL QUICHE ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '02', 'CHICHE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '03', 'CHINIQUE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '04', 'ZACUALPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '05', 'CHAJUL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '06', 'STO TOMAS CHICHICASTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '07', 'PATZITE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '08', 'SAN ANTONIO ILOTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '09', 'SAN PEDRO JOCOPILAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '10', 'CUNEN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '11', 'SAN JUAN COTZAL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '12', 'JOYABAJ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '13', 'NEBAJ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '14', 'SAN ANDRES SAJCABAJA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '15', 'SAN MIGUEL USPANTAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '16', 'SACAPULAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '17', 'SAN BARTOLOME JOCOTENANGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '18', 'CANILLA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '19', 'CHICAMAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '20', 'IXCAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '21', 'PACHALUN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (14, '22', 'PLAYA GRANDE');


--BAJA VERAPAZ
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (15, '01', 'SALAMA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (15, '02', 'SAN MIGUEL CHICAJ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (15, '03', 'RABINAL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (15, '04', 'CUBULCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (15, '05', 'GRANADOS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (15, '06', 'SANTA CRUZ EL CHOL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (15, '07', 'SAN JERONIMO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (15, '08', 'PURULHA');


--ALTA VERAPAZ
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '01', 'COBAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '02', 'SANTA CRUZ VERAPAZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '03', 'SAN CRISTOBAL VERAPAZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '04', 'TACTIC');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '05', 'TAMAHU');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '06', 'SAN MIGUEL TUCURU ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '07', 'PANZOS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '08', 'SENAHU');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '09', 'SAN PEDRO CARCHA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '10', 'SAN JUAN CHAMELCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '11', 'LANQUIN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '12', 'SANTA MARIA CAHABON');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '13', 'CHISEC');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '14', 'CHAHAL');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '15', 'FRAY BARTOLOME DE LAS CASAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '16', 'LA TINTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (16, '17', 'RAXRUHÁ');

--PETEN
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '01', 'FLORES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '02', 'SAN JOSE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '03', 'SAN BENITO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '04', 'SAN ANDRES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '05', 'LA LIBERTAD');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '06', 'SAN FRANCISCO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '07', 'SANTA ANA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '08', 'DOLORES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '09', 'SAN LUIS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '10', 'SAYAXCHE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '11', 'MELCHOR DE MENCOS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (17, '12', 'POPTUN');

--IZABAL
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (18, '01', 'PUERTO BARRIOS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (18, '02', 'LIVINGSTON');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (18, '03', 'EL ESTOR');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (18, '04', 'MORALES');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (18, '05', 'LOS AMATES');


--ZACAPA
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '01', 'ZACAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '02', 'ESTANZUELA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '03', 'RIO HONDO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '04', 'GUALAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '05', 'TECULUTAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '06', 'USUMATLAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '07', 'CABANAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '08', 'SAN DIEGO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '09', 'LA UNION');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (19, '10', 'HUITE');


--CHIQUIMULA
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '01', 'CHIQUIMULA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '02', 'SAN JOSE LA ARADA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '03', 'SAN JUAN LA ERMITA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '04', 'JOCOTAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '05', 'CAMOTAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '06', 'OLOPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '07', 'ESQUIPULAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '08', 'CONCEPCION LAS MINAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '09', 'QUEZALTEPEQUE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '10', 'SAN JACINTO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (20, '11', 'IPALA');



--JALAPA
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (21, '01', 'JALAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (21, '02', 'SAN PEDRO PINULA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (21, '03', 'SAN LUIS JILOTEPEQUE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (21, '04', 'SAN MANUEL CHAPARRON');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (21, '05', 'SAN CARLOS ALZATATE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (21, '06', 'MONJAS');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (21, '07', 'MATAQUESCUINTLA');


--22 - JUTIAPA 
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '01', 'JUTIAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '02', 'EL PROGRESO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '03', 'SANTA CATARINA MITA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '04', 'AGUA BLANCA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '05', 'ASUNCION MITA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '06', 'YUPILTEPEQUE');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '07', 'ATESCATEMPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '08', 'JEREZ');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '09', 'EL ADELANTO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '10', 'ZAPOTITLAN');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '11', 'COMAPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '12', 'JALPATAGUA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '13', 'CONGUACO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '14', 'MOYUTA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '15', 'PASACO');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '16', 'SAN JOSE ACATEMPA');
INSERT INTO MUNICIPIO(DEPARTAMENTO, CODIGO, NOMBRE) VALUES (22, '17', 'QUESADA');



SELECT * FROM MUNICIPIO