-- Insertar datos en la tabla PROVEEDOR
INSERT INTO PROVEEDOR (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    NIT,
    DPI,
    EMAIL,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Alimentos',
    'Alimentos',
    'SA',
    'SA',
    NULL,
    '15ta Avenida',
    'Vista Hermosa',
    'Zona 15',
    'Ciudad de Guatemala',
    1,
    1,
    '01015',
    '5555-5555',
    '123456789',
    '1234567890123',
    'alimentos@gmail.com',
    6,
    6,
    '',
    1
);

-- Insertar datos en la tabla PROVEEDOR
INSERT INTO PROVEEDOR (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    NIT,
    DPI,
    EMAIL,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Carnes',
    'Carnes',
    'SA',
    'SA',
    NULL,
    '16ta Avenida',
    'Vista Hermosa',
    'Zona 15',
    'Ciudad de Guatemala',
    1,
    1,
    '01015',
    '5555-4444',
    '1234590101',
    '12367890101',
    'carnes@gmail.com',
    6,
    6,
    '',
    1
);

-- Insertar datos en la tabla PROVEEDOR
INSERT INTO PROVEEDOR (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    NIT,
    DPI,
    EMAIL,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Mariscos',
    'Mariscos',
    'SA',
    'SA',
    NULL,
    '17ta Avenida',
    'Vista Hermosa',
    'Zona 15',
    'Ciudad de Guatemala',
    1,
    1,
    '01015',
    '3333-3333',
    '3337890101',
    '3333467890101',
    'mariscos@gmail.com',
    6,
    6,
    '',
    1
);

-- Insertar datos en la tabla PROVEEDOR
INSERT INTO PROVEEDOR (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    NIT,
    DPI,
    EMAIL,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Frutas',
    'Frutas',
    'SA',
    'SA',
    NULL,
    '18ta Avenida',
    'Vista Hermosa',
    'Zona 15',
    'Ciudad de Guatemala',
    1,
    1,
    '01015',
    '1111-1111',
    '7889786789',
    '788978678990',
    'frutas@gmail.com',
    6,
    6,
    '',
    1
);

-- Insertar datos en la tabla PROVEEDOR
INSERT INTO PROVEEDOR (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    NIT,
    DPI,
    EMAIL,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Truper',
    'Truper',
    'SA',
    'SA',
    NULL,
    '10ta Avenida',
    'Vista Hermosa',
    'Zona 15',
    'Ciudad de Guatemala',
    1,
    1,
    '01015',
    '4545-4545',
    '102197867',
    '3264190170101',
    'truperlatam@gmail.com',
    6,
    6,
    '',
    1
);