-- ADMINISTRADOR
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 1);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 2);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 3);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 4);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 5);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 6);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 7);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 8);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (1, 9);

-- VENDEDOR
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (2, 4);
INSERT INTO ROLACCESO (ID_ROL, ID_ACCESO) VALUES (2, 7);
