INSERT INTO CLIENTE(
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    EMAIL,
    NIT,
    DPI,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Luis',
    'Alfonso',
    'Arreaga',
    'Estrada',
    NULL,
    '7ma calle',
    NULL,
    'Zona 10',
    'Ciudad de Guatemala',
    1,
    1,
    '01010',
    '78673134',
    'luisA@gmail.com',
    '7789097865',
    '1234390780101',
    6,
    6,
    '',
    1
);

-- Insertar otro cliente en la tabla CLIENTE
INSERT INTO CLIENTE (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    EMAIL,
    NIT,
    DPI,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Carlos',
    'Roberto',
    'Gonzalez',
    'Lopez',
    'Martinez',
    '15ta avenida',
    'Vista Hermosa',
    'Zona 15',
    'Ciudad de Guatemala',
    1,
    1,
    '01015',
    '78341234',
    'carlosG@gmail.com',
    '778911234',
    '2345123456789',
    6,
    6,
    '',
    1
);

-- Insertar otro cliente en la tabla CLIENTE
INSERT INTO CLIENTE (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    EMAIL,
    NIT,
    DPI,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Ana',
    'Isabel',
    'Rodriguez',
    'Perez',
    NULL,
    '3ra Avenida',
    'Centro',
    'Zona 1',
    'Quetzaltenango',
    1,
    9,
    '09001',
    '78901234',
    'anaR@gmail.com',
    '778901234',
    '3456123456789',
    6,
    6,
    '',
    1
);

-- Insertar otro cliente en la tabla CLIENTE
INSERT INTO CLIENTE (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    EMAIL,
    NIT,
    DPI,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Kimberly',
    'Isabel',
    'Ortega',
    'Quiroz',
    NULL,
    '3ra Avenida',
    'Centro',
    'Zona 10',
    'Ciudad de Guatemala',
    1,
    1,
    '01010',
    '41412144',
    'kimberlyI@gmail.com',
    '456789877665',
    '3456123450101',
    6,
    6,
    '',
    1
);

-- Insertar otro cliente en la tabla CLIENTE
INSERT INTO CLIENTE (
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    OTROS_APELLIDOS,
    CALLE,
    COLONIA,
    ZONA,
    CIUDAD,
    MUNICIPIO,
    DEPARTAMENTO,
    CODIGO_POSTAL,
    TELEFONO,
    EMAIL,
    NIT,
    DPI,
    USUARIO_CREACION,
    USUARIO_MOD,
    FECHA_MOD,
    ESTADO
) VALUES (
    'Eduardo',
    'Pedro',
    'Rocas',
    'Rios',
    NULL,
    '4ta avenida 6-77',
    'Santiaguito',
    'Zona 1',
    'San marcos',
    4,
    12,
    '01010',
    '41412144',
    'eduardoP@gmail.com',
    '1024567890',
    '3567123450901',
    6,
    6,
    '',
    1
);