INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('01', 'GUATEMALA');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('02', 'EL PROGRESO');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('03', 'SACATEPEQUEZ');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('04', 'CHIMALTENANGO');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('05', 'ESCUINTLA');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('06', 'SANTA ROSA');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('07', 'SOLOLA');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('08', 'TOTONICAPAN');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('09', 'QUETZALTENANGO ');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('10', 'SUCHITEPEQUEZ');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('11', 'RETALHULEU');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('12', 'SAN MARCOS');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('13', 'HUEHUETENANGO');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('14', 'QUICHE');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('15', 'BAJA VERAPAZ');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('16', 'ALTA VERAPAZ');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('17', 'PETEN');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('18', 'IZABAL');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('19', 'ZACAPA');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('20', 'CHIQUIMULA');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('21', 'JALAPA');
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('22', 'JUTIAPA');

SELECT * FROM DEPARTAMENTO
